//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecflowPages.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecflowPages.Helpers.MarsResource", typeof(MarsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\GitHub\Advance Task_SpecFlow_MarsKimi\mars.specflow-master\SpecflowPages\Files\TestDataManageListings.xlsx.
        /// </summary>
        internal static string ManageListingPath {
            get {
                return ResourceManager.GetString("ManageListingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\GitHub\Advance Task_SpecFlow_MarsKimi\mars.specflow-master\SpecflowPages\TestReports\Test.html.
        /// </summary>
        internal static string ReportPath {
            get {
                return ResourceManager.GetString("ReportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\GitHub\Advance Task_SpecFlow_MarsKimi\mars.specflow-master\SpecflowPages\TestReports\ReportXML.xml.
        /// </summary>
        internal static string ReportXMLPath {
            get {
                return ResourceManager.GetString("ReportXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\GitHub\Advance Task_SpecFlow_MarsKimi\mars.specflow-master\SpecflowPages\Files\SampleTest.txt.
        /// </summary>
        internal static string SampleWorkPath {
            get {
                return ResourceManager.GetString("SampleWorkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\GitHub\Advance Task_SpecFlow_MarsKimi\mars.specflow-master\SpecflowPages\TestReports\Screenshots\Kimi\.
        /// </summary>
        internal static string ScreenShotPath {
            get {
                return ResourceManager.GetString("ScreenShotPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\GitHub\Advance Task_SpecFlow_MarsKimi\mars.specflow-master\SpecflowPages\Files\TestDataShareSkill.xlsx.
        /// </summary>
        internal static string ShareSkillPath {
            get {
                return ResourceManager.GetString("ShareSkillPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\GitHub\Advance Task_SpecFlow_MarsKimi\mars.specflow-master\SpecflowPages\Files\TestData.xlsx.
        /// </summary>
        internal static string TestDataPath {
            get {
                return ResourceManager.GetString("TestDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:5000/.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
